config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :item_name, presence: true
  validates :available, presence: true
  validates :price, presence: true
  validates :description, presence: true
  
  has_rich_text :description
  has_many_attached :images

  def sms_alert
    require 'net/http'
    require 'json'

    api_key = Rails.application.credentials.beem[:api_key]
    secret_key = Rails.application.credentials.beem[:secret_key]
    source_addr = "http://localhost:3000"
    body = {
      'source_addr': source_addr,
      'schedule_time': '',
      'encoding': '0',
      'message': 'SMS Test from Ruby API.',
      'recipients': [
      {
      'recipient_id': 1,
      'dest_addr': '255655719784', # this will change with the mobile number of the user
      },
      ],
      }
    uri = URI('https://apisms.beem.africa/v1/send')
    req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json', 'Authorization' => ('Basic ' + api_key + ':' + secret_key))
    req.body = body.to_json
    # res = Net::HTTP.start(uri.hostname, uri.port) do |http|
    #   http.request(req)
    # end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :mobile_number])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def welcome
    @user = current_user
    @products = Product.all.limit(3)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      @product.sms_alert
      flash[:notice] = "Please check the sms send to your mobile number"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def product_params
    params.require(:product).permit(:item_name, :price, :available, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/welcome.html.haml
- if user_signed_in?
  .row
    .col.s3
      %ul.collection.with-header
        %li.collection-header
          Welcome
          = @user.full_name
        %li.collection-item
          = link_to new_product_path do
            %i.material-icons.left new_label
            Register New Product
    .col.s9
      %ul 
        - @products.each do |product|
          %li
            = product.item_name
      
   

app/views/layouts/_flash_messages.html.haml
- flash.each do |name, msg|
  - if name.is_a?(String)
    %div{:class => "card-panel #{name.to_s == 'notice' ? 'green darken-1 white-text' : 'red darken-1 white-text'}"}
      -# %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} x
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
%nav.teal.darken-3
  .nav-wrapper
    = link_to root_path, class: "brand-logo ml-2" do
      E-Dukani
    %ul#nav-mobile.right.hide-on-med-and-down
      - if user_signed_in?
        %li
          = link_to destroy_user_session_path, class: "btn waves-effect waves-light red darken-1", method: :delete  do
            %i.material-icons.right logout
            Log out     
      - else
        %li
          = link_to new_user_session_path, class: "btn waves-effect waves-light green darken-1"  do
            %i.material-icons.right login
            Log in  
        %li
          = link_to new_user_registration_path, class: "btn waves-effect waves-light blue darken-1"  do
            %i.material-icons.right person_add
            Sign up

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EDukani
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
  %body
    = render 'layouts/navbar'
    = render 'layouts/flash_messages'
    = yield

app/views/products/_form.html.haml
= simple_form_for @product do |f|
  = f.error_notification
  = f.input :item_name
  = f.input :available
  = f.input :price
  = f.label :description
  = f.rich_text_area :description
  .card.cyan.lighten-5
    .card-content
      .card-title.center-align.teal-text.darken-3 Images
      = f.file_field :images, multiple: true, direct_upload: true
  = f.button :submit

app/views/products/new.html.haml
.container
  %h1 New Product
  = render 'form'